### ISSUE TITLE
Find Keyed Frame stops on incorrect frames

### ISSUE THREAD

**Issue by josephsdaniels** [aldrinsartfactory/stopmagic#1]
When I move a keyframe on the timeline, it still stops on the frame that previously had a key when using Find Previous or Find Next to move through the timeline, even though there is no longer a key there.

This is also the case if I make edits or sculpts on a frame in between key poses. Say I have a key pose on frame one and 5. If I edit the first key pose on say frame 2, the next time I step through my animation using Find Keyed Frame it will stop on frame 2 even though there is no key there.  Neither re-opening the file nor re-starting blender fixes the issue.

**Comment by aldrinmathew** [comment]
This has been fixed @josephsdaniels 

#### Here is the explanation:
The Find Keyed Frame feature was not just considering the actual keyframes present in the current scene. A keyframe will have an `x` and `y` coordinate. The `x` coordinate is indeed the actual value of the keyframe. The y coordinate is the value of the animation or the value that has been keyed.
So when all these values were returned by the function that found keyframes with keyed meshes, it jumped to the wrong frame

**Comment by aldrinmathew** [comment]
Also thanks for the detailed description.
And have a look at #3 . It is a serious issue if you are using dyntopology

**Comment by josephsdaniels** [comment]
Thanks so much for these fixes. It's a much smoother experience now 👍
