### ISSUE TITLE
Blender 3.2 - addon does not install

### ISSUE THREAD

**Issue by 3dcinetv** [aldrinsartfactory/stopmagic#10]
Hello, is there planned support for this addon in Blender 3.x+?

**Comment by AldrinMathew** [comment]
@3dcinetv 
Can you mention the error message you get while installing the addon?

**Comment by aldrinmathew** [comment]
@3dcinetv 
I installed the addon in latest build of `Blender 3.2.0` and there were no issues during installation or during usage.
And yes, this addon will be supported in `Blender 3.x+`, as of now, there are no API changes in the latest Blender versions that affects the functionality of the addon.
This is however my understanding of the API and latest versions. If any user bumps into any issues with the addon for any version of Blender past `2.91`, they can open an issue [here](https://github.com/aldrinsartfactory/stopmagic/issues/new) and the problem will will be taken care of.

**Comment by aldrinmathew** [comment]
Closing this as there is no feedback on installation errors and as I was not able to replicate the issue on my end. If any other users are having problems, make sure to report here and this will be reopened.

**Comment by 3dcinetv** [comment]
I confirm, it is working normally. I unzipped the content, navigated to the folder, extracted, re-zipped it, installed it on Blender, now it runs. Thank you very much.

**Comment by 3dcinetv** [comment]
this is the error: https://imgur.com/a/ZHmHWu0

Traceback (most recent call last):
  File "E:\Program Files\Blender-3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\stopmagic-main\__init__.py", line 13, in <module>
    from stopmagic import preferences
ModuleNotFoundError: No module named 'stopmagic'

I cannot install it on Blender 3.2. Please let me know what components it is missing. Thanks.

**Comment by 3dcinetv** [comment]
I unpacked the downloaded .zip. 
Unpacked the content.
Navigated to stopmagic folder. recompress to .zip (so the addon will access the files needed instead of readme.md, etc..)
I proceeded to install normally through the preferences>addon>install> (target stop magic). Nothing happened. No modules installed.
I created a mesh, went to edit mode, sculpt mode, nothing happened, I don't see the panel.
I'm using Blender 3.2 from monday's update.

Maybe a short video about its use, could be really helpful as well. 
The "install" instructions are generic, yet this problem might be related to other addons causing conflict with the current shortcuts and can cause the error at the time of install?

**Comment by aldrinmathew** [comment]
It could be a conflict with the shortcuts of other addons. Let me look into this.

**Comment by aldrinmathew** [comment]
@3dcinetv 
By the way, don't clone or download the repository as a zip to download the addon. Instead, go to the [latest release](https://github.com/aldrinsartfactory/stopmagic/releases/latest) page to download the addon. Also once you install the addon, if you have a network connection in your computer, the addon will notify you of any new versions and also automatically download the latest version when you click the upgrade button, so you don't have to manually check every time for a release.

**Comment by aldrinmathew** [comment]
@3dcinetv
Just checked if it is the conflict with existing shortcuts. I assigned shortcut for an operator and installed the addon without problems. So there is no problem with conflicts with existing keymaps for native operators.
I am not sure if Blender handles keymaps for addons in a different manner. Will have to look into this.

**Comment by 3dcinetv** [comment]
Thank you for your assistance. I confirm, I downloaded the addon from the "latest release page" and it installed at once. I confirm it works with Blender 2.3.
Just to confirm: the workflow is:
1. Set a keymesh frame
2. deform the keymesh frame

Correct?

**Comment by aldrinmathew** [comment]
@3dcinetv
Yep. That's it. Also make sure you use shortcuts as you progress for faster workflows. Each button will show the associated shortcuts. You can also duplicate keyframes, but **must** insert a new keymesh frame to detach mesh data from previous frame, otherwise any modifications will also affect the keyframe which you duplicated.
I will make a video soon explaining everything about the addon.

**Comment by aldrinmathew** [comment]
I am closing this as the original issue seems to be related to a specific build of Blender (especially since `3.2` in alpha) rather than the addon itself. At least that's the conclusion from the current available information. Anyone else facing similar issue can report a new issue or comment here to proceed.

**Comment by 3dcinetv** [comment]
Thank you. It's been solved. I'm doing a video tutorial for other blender artists to use this addon and visit your page.
