### ISSUE TITLE
Request: Onion Skin based on number of previous Poses, not Frames

### ISSUE THREAD

**Issue by josephsdaniels** [aldrinsartfactory/stopmagic#6]
As an animator, I'm not sure I'd ever want onionskin numbers to be based on timeline frames.  Instead I'm usually looking to show 1 or 2 previous and next Poses.  Because in stop motion, like in hand drawn animation, we typically use variable frame rates (meaning we'll have some keys on 1's, some on 2's, and so forth) locking onion skinning to frames makes for an inconsistent visual experience.  Not sure if this is a trivial request, but it would be much appreciated.  It could even be an option to switch between frames vs poses, with poses being the default.  Cheers!

**Comment by aldrinmathew** [comment]
Well bingo. This is already an upcoming feature, have been working on it even before `0.3.0-beta`. Keep this open and I will provide updates.

**Comment by aldrinmathew** [comment]
This feature has been added in 3db6176bb15ce2f2c43c9909570a912cc90daf99 and also the logic for Onion Skin has been rewritten and improved.
This will reflect in the next deployment
