### ISSUE TITLE
Sometimes, turning on Onion Skinning sets mesh to flat-shaded

### ISSUE THREAD

**Issue by josephsdaniels** [aldrinsartfactory/stopmagic#7]
Inconsistent Issue:
I can't produce it consistently yet, but every few minutes, when I enable Onion Skin that specific mesh frame will be switched to flat shading when the mesh was previously smooth-shaded.

Consistent Issue:
It also toggles some viewport shading options. For instance I am currently working in Workbench viewport mode, and have Color set to Vertex color.  Upon enabling Onion Skin, it changes back to the default which is Object.  I've tested and can confirm that no matter what option I set for Color in the Viewport Shading menu, it will revert to Object once Onion Skin is enabled.

**Comment by aldrinmathew** [comment]
Well yeah the automatic switching was to make sure that the onion objects had a lesser opacity compared to the main object. But yeah not a great system to work with. Will provide updates on this soon.

**Comment by aldrinmathew** [comment]
A new feature for the addon will set the display colors and materials for the onion objects appropriately, without changing shading type and disrupting user's workflow. This will land in the next release
